{
 "title": "Application dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(http_requests_total{status_code=~\"5..\"}[10m]))\r\n/\r\nsum(rate(http_requests_total[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}