{
 "title": "Infra dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{datname=\"postgres\"}[5m]))\r\n+\r\nsum(rate(pg_stat_database_xact_rollback{datname=\"postgres\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk useage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 -\r\n  node_filesystem_avail_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"}\r\n  /\r\n  node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 -\r\n  node_memory_MemAvailable_bytes\r\n  /\r\n  node_memory_MemTotal_bytes\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - (\r\n  avg by (instance) (\r\n    rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n  ) * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}