on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running manually'
        required: false
        default: 'Manual health check'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Build
        run: |
          docker build -t app:test ./crud-rest-api

      - name: Run tests
        run: |
          docker compose -f crud-rest-api/docker-compose.test.yml up -d node_db_test
          docker compose -f crud-rest-api/docker-compose.test.yml run --rm node_app_test npm test

      - name: Cleanup
        if: always()
        run: docker compose -f crud-rest-api/docker-compose.test.yml down -v