on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running manually'
        required: false
        default: 'Manual health check'

permissions:
  id-token: write
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      # run only test db and the run jest tests in temp container and delete it
      - name: Run tests
        run: |
          docker compose -f crud-rest-api/docker-compose.test.yml up -d node_db_test 
          docker compose -f crud-rest-api/docker-compose.test.yml run --rm node_app_test npm test

      - name: Cleanup
        if: always()
        run: docker compose -f crud-rest-api/docker-compose.test.yml down -v

  build-push:
    if: github.event_name == 'push'
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: config aws creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/github-actions-role
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build -t app:${{ github.sha }} ./crud-rest-api

      - name: Tag image
        run: |
          docker tag app:${{ github.sha }} \
            ${{ secrets.AWS_ID }}.dkr.ecr.us-east-1.amazonaws.com/app_repo:${{ github.sha }}

      - name: Push image
        run: |
          docker push \
            ${{ secrets.AWS_ID }}.dkr.ecr.us-east-1.amazonaws.com/app_repo:${{ github.sha }}

  deploy-staging:
      if: github.event_name == 'push'
      needs: build-push
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/github-actions-role
            aws-region: us-east-1

        - name: Find instance ID
          run: |
            INSTANCE_ID=$(aws ec2 describe-instances \
              --filters \
                "Name=tag:Project,Values=8byte-devops-assignment" \
                "Name=tag:Environment,Values=staging" \
                "Name=instance-state-name,Values=running" \
              --query "Reservations[0].Instances[0].InstanceId" \
              --output text)

            echo "INSTANCE_ID=$INSTANCE_ID" >> "$GITHUB_ENV"

        - name: Deploy to staging
          run: |
            COMMAND_ID=$(aws ssm send-command \
              --instance-ids "$INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --parameters 'commands=[
                "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ID }}.dkr.ecr.us-east-1.amazonaws.com",
                "docker pull ${{ secrets.AWS_ID }}.dkr.ecr.us-east-1.amazonaws.com/app_repo:${{ github.sha }}",
                "docker stop app || true",
                "docker rm app || true",
                "docker run -d --name app -p 3000:3000 --restart unless-stopped ${{ secrets.AWS_ID }}.dkr.ecr.us-east-1.amazonaws.com/app_repo:${{ github.sha }}"
              ]' \
              --region us-east-1 \
              --query "Command.CommandId" \
              --output text)

            aws ssm wait command-executed \
              --command-id "$COMMAND_ID" \
              --instance-id "$INSTANCE_ID"